package com.auction.common.protocol;

public enum MessageType {
    REGISTER,
    LOGIN,
    LOGOUT,

    GET_DASHBOARD,
    GET_AUCTIONS,
    GET_AUCTION_DETAIL,

    CREATE_ITEM,
    UPDATE_ITEM,
    DELETE_ITEM,

    CREATE_AUCTION,
    UPDATE_AUCTION,
    CANCEL_AUCTION,

    PLACE_BID,
    GET_BID_HISTORY,

    SUBSCRIBE_AUCTION,
    UNSUBSCRIBE_AUCTION,

    BID_UPDATE,
    AUCTION_CLOSED,
    TIME_EXTENDED,

    ADMIN_GET_USERS,
    ADMIN_UPDATE_USER_STATUS,
    ADMIN_GET_AUCTIONS
}
